<?xml version="1.0" ?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                version="1.0">

<?spec xslt#copy-of?>
<!-- BUG 6.0/001 -->
<!-- DESCRIPTION: Invalid attribute prefix generated by xsl:copy-of -->

  <xsl:template match='/'>
    <xsl:copy-of select='.'/>
  </xsl:template>


</xsl:stylesheet >

